### ISSUE TITLE
Permissions mixins/decorators

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#85] opened 2024-06-02 17:43 UTC
With tables and forms now scoped to PDU of the user, this needs enforcing with decorators or mixins.

**Comment by mbarton** [comment] 2024-06-04 14:19
@eatyourpeas dupe of https://github.com/rcpch/national-paediatric-diabetes-audit/issues/13?

**Comment by mbarton** [comment] 2024-07-16 14:23
This is now implemented

**Closed as completed by mbarton** 2024-07-16 14:23 UTC
Labels: feature, help wanted
