### ISSUE TITLE
Calculations for the data completeness report

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/national-paediatric-diabetes-audit#137] opened 2024-06-21 12:23 UTC
Here are the calculations for the DCR (data completeness report) - let me know if anything's unclear.

**Comment by AmaniKrayemRCPCH** [comment] 2024-06-21 12:24
[Calculations_AK_20240621.xlsx](https://github.com/user-attachments/files/15927723/Calculations_AK_20240621.xlsx)

**Comment by mbarton** [comment] 2024-07-18 12:57
Dupe of #88

**Closed as completed by mbarton** 2024-07-18 12:57 UTC
