### ISSUE TITLE
Access-token expired

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#222] opened 2024-07-27 18:33 UTC
Noted 500 error on staging site.
Logs below
```
django.db.utils.OperationalError: connection to server at "npda-staging.postgres.database.azure.com" (172.167.156.116), port 5432 failed: FATAL:  The access token has expired. Please acquire a new token and retry.
connection to server at "xxxxxx" (xxx.xxx.xxx.xxx), port xxx failed: FATAL:  no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "xxxx", database "xxxx", no encryption
```

**Comment by mbarton** [comment] 2024-07-28 09:26
Probably a dupe of https://github.com/rcpch/national-paediatric-diabetes-audit/issues/207?

**Comment by mbarton** [comment] 2024-08-19 09:27
Fixed in https://github.com/rcpch/national-paediatric-diabetes-audit/pull/242

**Closed as completed by mbarton** 2024-08-19 09:27 UTC
Labels: bug
