### ISSUE TITLE
default.csv is causing a 500 error in live

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#305] opened 2024-10-06 18:00 UTC
In the staging instance submission tab is trying to load default.csv
This is generating an error

**Comment by mbarton** [comment] 2024-10-16 13:41
Uploading a valid CSV also causes a 500 error. I'm having a look now

*Update*: the issue is a duplicate NHS number:

```
DETAIL:  Key (nhs_number)=(719 573 0220) already exists.
```

It thinks there are zero patients in the previous submission:

```
Deleting patients from previous submission: 0
```

I've cleared out all the submissions and patients and now it's working again.

@eatyourpeas when you mentioned `default.csv` in the issue description was that a separate issue from uploading CSVs not working generally in the staging instance?

**Comment by eatyourpeas** [comment] 2024-10-16 14:23
sorry possibly not thought it through. In the model default.csv is the default name, but the csv s are stored under a different name (I think the PDU with a timestamp). I had assumed if there was no CSV uploaded when navigating to submissions it was looking for default.csv which did not exist.

**Comment by mbarton** [comment] 2024-10-31 16:27
I think this is fixed now, please re-open if now

**Closed as completed by mbarton** 2024-10-31 16:27 UTC
